### PR TITLE
patch: add coming soon to unvailable products

### PR DESCRIPTION
**Pull request by tinashechiraya**

### CODE REVIEW

**Comment by tinashechiraya** [comment]
updated

this is the design I have added

**Comment by tinashechiraya** [comment]
no_prices

other design

**Comment by tinashechiraya** [comment]
@meomancer this pr was also resolved @amyburness mentioned we can stick to the first design since its consistent with the website styles so you can merge this

**Comment by LenevJ** [comment]
> updated
> 
> this is the design I have added

@tinashechiraya This design is according to the style guide, so please stick with this. One thing I noticed is that the colour of the coming soon banner seems to be a different blue from that of the price card blue. I don't know if it's just something strange happening to my screen but please just double check that it is the same blue.

**Comment by LenevJ** [comment]
> no_prices
> 
> other design

@tinashechiraya This version doesn't adhere to the style we've been using throughout. The red is also not really a colour we include (except in error messages). Stick with the first design with blue corner banner.

**Comment by meomancer** [comment]
Thank you @tinashechiraya

**Pull request merged**
